### ISSUE TITLE
Openstack credential create failed : Internal server error

### ISSUE THREAD

**Issue by mike00151** [sequenceiq/cloudbreak-deployer#44]
Hello

Here is my deploy step

```curl https://raw.githubusercontent.com/sequenceiq/cloudbreak-deployer/master/install | sh```

```cbd update```

```cbd generate```

```cbd start```

And I failed to credential my private openstack.

It appears "Openstack credential create failed : Internal server error" on UI

Here is the logs from cdb logs commands

```
cloudbreak_1    | 2015-05-04 14:00:20,456 [http-nio-8080-exec-6] serverError:93 ERROR c.s.c.c.ExceptionControllerAdvice - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] Failed to convert from type com.sequenceiq.cloudbreak.controller.json.CredentialJson to type com.sequenceiq.cloudbreak.domain.OpenStackCredential for value 'com.sequenceiq.cloudbreak.controller.json.CredentialJson@4df90256'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.jasypt.encryption.pbe.PBEStringCleanablePasswordEncryptor] is defined: expected single matching bean but found 2: pbeStringCleanablePasswordEncryptor,encryptor
cloudbreak_1    | org.springframework.core.convert.ConversionFailedException: Failed to convert from type com.sequenceiq.cloudbreak.controller.json.CredentialJson to type com.sequenceiq.cloudbreak.domain.OpenStackCredential for value 'com.sequenceiq.cloudbreak.controller.json.CredentialJson@4df90256'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.jasypt.encryption.pbe.PBEStringCleanablePasswordEncryptor] is defined: expected single matching bean but found 2: pbeStringCleanablePasswordEncryptor,encryptor
cloudbreak_1    |       at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:158) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.controller.CredentialController.convert(CredentialController.java:174) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.controller.CredentialController.createCredential(CredentialController.java:156) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.controller.CredentialController.savePrivateCredential(CredentialController.java:55) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
cloudbreak_1    |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
cloudbreak_1    |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
cloudbreak_1    |       at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
cloudbreak_1    |       at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) ~[spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870) ~[spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961) [spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863) [spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837) [spring-webmvc-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilter(WebRequestTraceFilter.java:115) [spring-boot-actuator-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextFilterConfiguration$1.doFilterInternal(EndpointWebMvcAutoConfiguration.java:137) [spring-boot-actuator-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.conf.SecurityConfig$ScimAccountGroupReaderFilter.doFilterInternal(SecurityConfig.java:154) [cloudbreak.jar!/:na]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:140) [spring-security-oauth2-2.0.3.RELEASE.jar!/:na]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [spring-security-web-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:85) [spring-boot-actuator-1.0.2.RELEASE.jar!/:1.0.2.RELEASE]
cloudbreak_1    |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) [spring-web-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1721) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679) [tomcat-embed-core-7.0.52.jar!/:7.0.52]
cloudbreak_1    |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
cloudbreak_1    |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
cloudbreak_1    |       at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
cloudbreak_1    | Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.jasypt.encryption.pbe.PBEStringCleanablePasswordEncryptor] is defined: expected single matching bean but found 2: pbeStringCleanablePasswordEncryptor,encryptor
cloudbreak_1    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:970) ~[spring-beans-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:82) ~[spring-context-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187) ~[spring-aop-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at com.sun.proxy.$Proxy117.encrypt(Unknown Source) ~[na:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.converter.JsonToOpenStackCredentialConverter.convert(JsonToOpenStackCredentialConverter.java:25) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at com.sequenceiq.cloudbreak.converter.JsonToOpenStackCredentialConverter.convert(JsonToOpenStackCredentialConverter.java:12) ~[cloudbreak.jar!/:na]
cloudbreak_1    |       at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:353) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:35) ~[spring-core-4.0.3.RELEASE.jar!/:4.0.3.RELEASE]
cloudbreak_1    |       ... 88 common frames omitted
ambassador_1    | 2015/05/04 14:01:07 172.17.1.78:33907 -> node1.node.dc1.consul.:32838
```

Here is the generated ```docker-compose.yml``` file

```
consul:
    privileged: true
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "172.17.42.1:53:53/udp"
        - "8400:8400"
        - "8500:8500"
    hostname: node1
    image: sequenceiq/consul:v0.5.0-v3
    command: --server --bootstrap --advertise 172.17.42.1

registrator:
    privileged: true
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
    image: gliderlabs/registrator:v5
    links:
        - consul
    command: consul://consul:8500

ambassador:
    privileged: true
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    dns: 172.17.42.1
    image: progrium/ambassadord:latest
    command: --omnimode

ambassadorips:
    privileged: true
    net: container:ambassador
    image: progrium/ambassadord:latest
    command: --setup-iptables

uaadb:
    privileged: true
    ports:
        - 5432
    environment:
      - SERVICE_NAME=uaadb
        #- SERVICE_CHECK_CMD=bash -c 'psql -h 127.0.0.1 -p 5432  -U postgres -c "select 1"'
    volumes:
        - "/var/lib/cloudbreak/uaadb:/var/lib/postgresql/data"
    image: postgres:9.4.0

identity:
    ports:
        - 8089:8080
    environment:
        - SERVICE_NAME=identity
        # - SERVICE_CHECK_HTTP=/login
        - IDENTITY_DB_URL=mydb:5432
        - BACKEND_5432=uaadb.service.consul
    links:
        - ambassador:mydb
    volumes:
      - uaa.yml:/uaa/uaa.yml
    image: sequenceiq/uaa:1.8.1-v1

cbdb:
    ports:
        - 5432
    environment:
      - SERVICE_NAME=cbdb
        #- SERVICE_CHECK_CMD=bash -c 'psql -h 127.0.0.1 -p 5432  -U postgres -c "select 1"'
    volumes:
        - "/var/lib/cloudbreak/cbdb:/var/lib/postgresql/data"
    image: postgres:9.4.0

cloudbreak:
    environment:
        #- AWS_ACCESS_KEY_ID=
        #- AWS_SECRET_KEY=
        - SERVICE_NAME=cloudbreak
          #- SERVICE_CHECK_HTTP=/info
        - CB_CLIENT_ID=cloudbreak
        - CB_CLIENT_SECRET=8ea6a9f14a
        - CB_BLUEPRINT_DEFAULTS=multi-node-hdfs-yarn,lambda-architecture,hdp-multinode-default
        - CB_AZURE_IMAGE_URI=https://102589fae040d8westeurope.blob.core.windows.net/images/packer-cloudbreak-2015-03-10-centos6_2015-March-10_17-15-os-2015-03-10.vhd
        - CB_GCP_SOURCE_IMAGE_PATH=sequenceiqimage/sequenceiq-ambari17-consul-centos-2015-03-10-1449.image.tar.gz
        - CB_AWS_AMI_MAP=ap-northeast-1:ami-c528c3c5,ap-southeast-2:ami-e7c3b2dd,sa-east-1:ami-c5e55dd8,ap-southeast-1:ami-42c3f510,eu-west-1:ami-bb35a7cc,us-west-1:ami-4b20c70f,us-west-2:ami-eb1f3ddb,us-east-1:ami-00391e68
        - CB_OPENSTACK_IMAGE=packer-cloudbreak-centos-2015-03-11
          #- CB_HBM2DDL_STRATEGY=create
        - CB_SMTP_SENDER_USERNAME=
        - CB_SMTP_SENDER_PASSWORD=
        - CB_SMTP_SENDER_HOST=
        - CB_SMTP_SENDER_PORT=25
        - CB_SMTP_SENDER_FROM=
        - ENDPOINTS_AUTOCONFIG_ENABLED=false
        - ENDPOINTS_DUMP_ENABLED=false
        - ENDPOINTS_TRACE_ENABLED=false
        - ENDPOINTS_CONFIGPROPS_ENABLED=false
        - ENDPOINTS_METRICS_ENABLED=false
        - ENDPOINTS_MAPPINGS_ENABLED=false
        - ENDPOINTS_BEANS_ENABLED=false
        - ENDPOINTS_ENV_ENABLED=false
        - CB_IDENTITY_SERVER_URL=http://backend:8089
        - CB_DB_PORT_5432_TCP_ADDR=backend
        - CB_DB_PORT_5432_TCP_PORT=5432
        - BACKEND_5432=cbdb.service.consul
        - BACKEND_8089=identity.service.consul
    links:
        - ambassador:backend
    ports:
        - 8080:8080
    image: sequenceiq/cloudbreak:0.4.7
    command: bash

sultans:
    environment:
        - SL_CLIENT_ID=sultans
        - SL_CLIENT_SECRET=8ea6a9f14a
        - SERVICE_NAME=sultans
          #- SERVICE_CHECK_HTTP=/
        - SL_PORT=3000
        #- SL_SMTP_SENDER_HOST=
        #- SL_SMTP_SENDER_PORT=
        #- SL_SMTP_SENDER_USERNAME=
        #- SL_SMTP_SENDER_PASSWORD=
        #- SL_SMTP_SENDER_FROM=
        - SL_CB_ADDRESS=http://10.5.0.11:3000
        - SL_ADDRESS=http://10.5.0.11:3001
        - SL_UAA_ADDRESS=http://backend:8089
        - BACKEND_8089=identity.service.consul
    links:
        - ambassador:backend
    ports:
        - 3001:3000
    image: sequenceiq/sultans-bin:0.4.6

uluwatu:
    environment:
        - ULU_PRODUCTION=false
        - SERVICE_NAME=uluwatu
          #- SERVICE_CHECK_HTTP=/
        - ULU_OAUTH_REDIRECT_URI=http://10.5.0.11:3000/authorize
        - ULU_SULTANS_ADDRESS=http://10.5.0.11:3001
        - ULU_OAUTH_CLIENT_ID=uluwatu
        - ULU_OAUTH_CLIENT_SECRET=8ea6a9f14a
        - ULU_HOST_ADDRESS=http://10.5.0.11:3000
        - NODE_TLS_REJECT_UNAUTHORIZED=0

        - ULU_IDENTITY_ADDRESS=http://backend:8089/
        - ULU_CLOUDBREAK_ADDRESS=http://backend:8080
        - ULU_PERISCOPE_ADDRESS=http://backend:8085/
        - BACKEND_8089=identity.service.consul
        - BACKEND_8080=cloudbreak.service.consul
        - BACKEND_8085=periscope.service.consul
    links:
        - ambassador:backend
    ports:
        - 3000:3000
    image: sequenceiq/uluwatu-bin:0.4.7

pcdb:
    environment:
        - SERVICE_NAME=pcdb
     #- SERVICE_NAMEE_CHECK_CMD='psql -h 127.0.0.1 -p 5432  -U postgres -c "select 1"'
    ports:
        - 5432
    volumes:
        - /var/lib/cloudbreak/periscopedb:/var/lib/postgresql/data
    image: postgres:9.4.0

periscope:
    environment:
        - PERISCOPE_DB_HBM2DDL_STRATEGY=create
        - SERVICE_NAME=periscope
          #- SERVICE_CHECK_HTTP=/info
        - PERISCOPE_SMTP_HOST=
        - PERISCOPE_SMTP_USERNAME=
        - PERISCOPE_SMTP_PASSWORD=
        - PERISCOPE_SMTP_FROM=
        - PERISCOPE_SMTP_PORT=25
        - PERISCOPE_CLIENT_ID=periscope
        - PERISCOPE_CLIENT_SECRET=8ea6a9f14a
        - PERISCOPE_HOSTNAME_RESOLUTION=public
        - ENDPOINTS_AUTOCONFIG_ENABLED=false
        - ENDPOINTS_DUMP_ENABLED=false
        - ENDPOINTS_TRACE_ENABLED=false
        - ENDPOINTS_CONFIGPROPS_ENABLED=false
        - ENDPOINTS_METRICS_ENABLED=false
        - ENDPOINTS_MAPPINGS_ENABLED=false
        - ENDPOINTS_BEANS_ENABLED=false
        - ENDPOINTS_ENV_ENABLED=false
        - PERISCOPE_DB_TCP_ADDR=backend
        - PERISCOPE_DB_TCP_PORT=5433
        - PERISCOPE_CLOUDBREAK_URL=http://backend:8080
        - PERISCOPE_IDENTITY_SERVER_URL=http://backend:8089/
        - BACKEND_8080=cloudbreak.service.consul
        - BACKEND_5433=pcdb.service.consul
        - BACKEND_8089=identity.service.consul
    links:
        - ambassador:backend
    ports:
        - 8085:8080
    image: sequenceiq/periscope:0.4.2
```

And here is the generated ```uaa.yml``` file

```
spring_profiles: postgresql

database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${IDENTITY_DB_URL}/postgres
  username: ${IDENTITY_DB_USER:postgres}
  password: ${IDENTITY_DB_PASS:}

oauth:
  client:
    override: true
    autoapprove:
      - cloudbreak_shell
  clients:
    sultans:
      id: sultans
      secret: 8ea6a9f14a
      authorized-grant-types: client_credentials
      scope: scim.read,scim.write,password.write
      authorities: uaa.resource,scim.read,scim.write,password.write
    uluwatu:
      id: uluwatu
      secret: 8ea6a9f14a
      authorized-grant-types: authorization_code,client_credentials
      scope: cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,cloudbreak.templates,openid,password.write,cloudbreak.usages.global,cloudbreak.usages.account,cloudbreak.usages.user,cloudbreak.events,periscope.cluster,cloudbreak.recipes
      authorities: cloudbreak.subscribe
      redirect-uri: http://10.5.0.11:3000/authorize
    cloudbreak:
      id: cloudbreak
      secret: 8ea6a9f14a
      authorized-grant-types: client_credentials
      scope: scim.read,scim.write,password.write
      authorities: uaa.resource,scim.read,scim.write,password.write
    periscope:
      id: periscope
      secret: 8ea6a9f14a
      authorized-grant-types: client_credentials
      scope: none
      authorities: cloudbreak.autoscale,uaa.resource,scim.read
    cloudbreak_shell:
      id: cloudbreak_shell
      authorized-grant-types: implicit
      scope: cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,cloudbreak.events,cloudbreak.usages.global,cloudbreak.usages.account,cloudbreak.usages.user,cloudbreak.recipes,openid,password.write
      authorities: uaa.none
      redirect-uri: http://cloudbreak.shell

scim:
  username_pattern: '[a-z0-9+\-_.@]+'
  users:
    - admin@example.com|cloudbreak|admin@example.com|Joe|Admin|openid,cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,sequenceiq.cloudbreak.admin,sequenceiq.cloudbreak.user,sequenceiq.account.seq1234567.SequenceIQ,cloudbreak.events,cloudbreak.usages.global,cloudbreak.usages.account,cloudbreak.usages.user,periscope.cluster,cloudbreak.recipes
```

Here is my docker version

```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

And cbd with version command

```
0.1.0
latest version:
0.1.0
```
